# Generated by Django 4.1.7 on 2023-02-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcaseapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="meaning",
        ),
    ]
